[config]

[templates.tmux]
input_path = "~/.config/matugen/templates/tmux-colors.conf"
output_path = "~/.tmux/tmux-colors.conf"
post_hook = "tmux source-file ~/.tmux/tmux-colors.conf"

[templates.yazi]
input_path = "~/.config/matugen/templates/yazi-theme.toml"
output_path = "~/.config/yazi/flavors/matugen.yazi/flavor.toml"

[templates.mango]
input_path = "~/.config/matugen/templates/mango.conf"
output_path = "~/.config/mango/colors.conf"

[templates.nvim]
input_path = "~/.config/matugen/templates/nvim.lua"
output_path = "~/.config/nvim/lua/theme/colors.lua"
post_hook = "pkill -SIGUSR1 nvim"
